version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: circleci/node:4.8.2
    steps:
        - checkout
        - run: npm install -q
        - snyk/scan

workflows:
  example-workflow:
    jobs:
      - example-job