version: '2.1'
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - checkout
      - run:
          name: Snyk Scan Application files 
          command: npm install 
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: false
workflows: null
