version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build:
      docker:
      - image: cimg/node
      steps:
      - checkout
      - run:
          command: npm install -q
      - snyk/scan:
          token-variable: SNYK_TOKEN                                # use is api token stored in an env variable named other than SNYK_TOKEN
          severity-threshold: high                                  # only fail if detected high-severity vulnerabilities
          fail-on-issues: false                                     # don't fail even if issues detected (not recommended!)
          monitor-on-build: true                                    # create a snapshot of apps dependencies on snyk.io, for continoues monitoring (recommended!)
